services:
    _defaults:
        autowire: true
    Rd\AuthenticationBundle\:
        resource: '../../*'
        exclude: '../{DependencyInjection,Entity,Migrations,Tests}'
    Rd\AuthenticationBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    # Subscribers
    Rd\AuthenticationBundle\EventSubscriber\AuthenticationSubscriber:
        tags: ['kernel.event_subscriber']