services:
    _defaults:
        autowire: true
    Rd\AuthenticationBundle\:
        resource: '../../*'
        exclude: '../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
    Rd\AuthenticationBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']